
import { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Coins,
  Bank,
  Plus,
  PencilSimple,
  Info,
  Check,
} from '@phosphor-icons/react';

const getIncomeEntryDate = (entry, fallbackDate) => entry?.date || entry?.createdAt || fallbackDate;

const isSameMonth = (dateA, dateB) => {
  const a = new Date(dateA);
  const b = new Date(dateB);
  return a.getMonth() === b.getMonth() && a.getFullYear() === b.getFullYear();
};

const createPrimaryIncomeEntry = (amount, currentDate, source = 'Ingreso principal', frequency = 'monthly', anchorDate = null, incomeType = 'fixed') => ({
  id: 'income-primary-config',
  amount: Number(amount || 0),
  source,
  type: 'primary',
  frequency,
  date: currentDate,
  anchorDate: anchorDate || currentDate,
  isPrimaryConfig: true,
  incomeType,
  createdAt: currentDate
});

const formatSourceText = (value) => {
  if (!value) return '';
  const normalized = value.replace(/\s+/g, ' ').trimStart();
  return normalized.charAt(0).toUpperCase() + normalized.slice(1).toLowerCase();
};

const formatMoney = (value) => Number(value || 0).toLocaleString('es-MX', { minimumFractionDigits: 2 });

const getMonthlyIncomeContribution = (entry) => {
  const amount = Number(entry?.amount || 0);

  if (entry?.autoGenerated || entry?.type === 'primary-auto') {
    return amount;
  }

  const frequency = entry?.frequency || (entry?.type === 'primary' ? 'monthly' : 'one-time');

  if (frequency === 'weekly') return amount * 4.33;
  if (frequency === 'biweekly') return amount * 2;
  return amount;
};

const sanitizeSourceInput = (value) => value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñÜü\s]/g, '');

const frequencyLabels = {
  weekly: 'Semanal',
  biweekly: 'Quincenal',
  monthly: 'Mensual',
  'one-time': 'Único'
};

const incomeFrequencyOptions = [
  { value: 'weekly', label: 'Semanal' },
  { value: 'biweekly', label: 'Quincenal' },
  { value: 'monthly', label: 'Mensual' }
];

const getMonthlyCardPaymentsTotal = (payments = [], currentDate = new Date().toISOString()) => (
  (payments || [])
    .filter((payment) => {
      const paymentDate = new Date(payment.date || payment.createdAt || currentDate);
      const current = new Date(currentDate);
      return paymentDate.getMonth() === current.getMonth() && paymentDate.getFullYear() === current.getFullYear();
    })
    .reduce((sum, payment) => sum + Number(payment.amount || 0), 0)
);

const createEmptyIncomeForm = (currentDate) => ({
  amount: '',
  source: '',
  type: 'extra',
  date: new Date(currentDate).toISOString().split('T')[0]
});

const getPrimaryAnchorDateValue = (entry, currentDate) => {
  const rawValue = entry?.anchorDate || entry?.date || currentDate;
  return new Date(rawValue).toISOString().split('T')[0];
};

const getAutoDepositsForMonth = (entries = [], currentDate) => (
  (entries || []).filter((entry) => isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate) && (entry.autoGenerated || entry.type === 'primary-auto'))
);

const getNextCycleDate = (dateValue, frequency = 'monthly') => {
  const next = new Date(dateValue);
  next.setHours(12, 0, 0, 0);
  if (frequency === 'weekly') {
    next.setDate(next.getDate() + 7);
  } else if (frequency === 'biweekly') {
    next.setDate(next.getDate() + 14);
  } else {
    next.setMonth(next.getMonth() + 1);
  }
  return next;
};

const getLatestDueCycleDate = (anchorDate, frequency, currentDate) => {
  const current = new Date(currentDate);
  current.setHours(23, 59, 59, 999);
  const cursor = new Date(anchorDate);
  cursor.setHours(12, 0, 0, 0);

  if (Number.isNaN(cursor.getTime()) || cursor > current) return null;

  let latest = new Date(cursor);
  while (true) {
    const next = getNextCycleDate(latest, frequency);
    if (next > current) break;
    latest.setTime(next.getTime());
  }
  return latest;
};

const getCycleKey = (dateValue) => {
  const date = new Date(dateValue);
  date.setHours(12, 0, 0, 0);
  return date.toISOString().split('T')[0];
};

const getPendingVariableCycleInfo = (primaryEntry, entries = [], currentDate) => {
  if (!primaryEntry || (primaryEntry.incomeType || 'fixed') !== 'variable') return null;

  const latestDueDate = getLatestDueCycleDate(primaryEntry.anchorDate || primaryEntry.date || currentDate, primaryEntry.frequency || 'monthly', currentDate);
  if (!latestDueDate) return null;

  const cycleKey = getCycleKey(latestDueDate);
  const matchingEntry = (entries || []).find((entry) => entry.type === 'primary-variable-cycle' && entry.cycleAnchorDate === cycleKey);
  const nextCycleDate = getNextCycleDate(latestDueDate, primaryEntry.frequency || 'monthly');

  return {
    cycleKey,
    dueDate: latestDueDate,
    nextCycleDate,
    isPending: !matchingEntry,
    existingEntry: matchingEntry || null
  };
};

export default function IncomeModal({ isOpen, onClose, data, onUpdate }) {
  const { cash, currentDate, expenses = [] } = data;
  const monthEntries = useMemo(
    () => (cash?.entries || []).filter((entry) => isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate)),
    [cash?.entries, currentDate]
  );
  const primaryEntry = (cash?.entries || []).find((entry) => entry.type === 'primary' || entry.isPrimaryConfig) || monthEntries.find((entry) => entry.type === 'primary');

  const [primaryIncome, setPrimaryIncome] = useState(primaryEntry?.amount?.toString() || cash?.income?.toString() || '0');
  const [primaryFrequency, setPrimaryFrequency] = useState(primaryEntry?.frequency || 'monthly');
  const [primaryIncomeType, setPrimaryIncomeType] = useState(primaryEntry?.incomeType || 'fixed');
  const [primaryPayDate, setPrimaryPayDate] = useState(getPrimaryAnchorDateValue(primaryEntry, currentDate));
  const [entries, setEntries] = useState(cash?.entries || []);
  const [incomeForm, setIncomeForm] = useState(createEmptyIncomeForm(currentDate));
  const [showPrimaryIncomeForm, setShowPrimaryIncomeForm] = useState(false);
  const [showAdditionalIncomeForm, setShowAdditionalIncomeForm] = useState(false);
  const [primarySaved, setPrimarySaved] = useState(false);
  const [incomeError, setIncomeError] = useState('');
  const [variableCycleAmount, setVariableCycleAmount] = useState('');
  const [flowStep, setFlowStep] = useState(1);
  const [incomeFlow, setIncomeFlow] = useState('primary');

  useEffect(() => {
    if (!isOpen) return;
    const freshMonthEntries = (cash?.entries || []).filter((entry) => isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate));
    const freshPrimary = (cash?.entries || []).find((entry) => entry.type === 'primary' || entry.isPrimaryConfig) || freshMonthEntries.find((entry) => entry.type === 'primary');
    setPrimaryIncome(freshPrimary?.amount?.toString() || '0');
    setPrimaryFrequency(freshPrimary?.frequency || 'monthly');
    setPrimaryIncomeType(freshPrimary?.incomeType || 'fixed');
    setPrimaryPayDate(getPrimaryAnchorDateValue(freshPrimary, currentDate));
    setEntries(cash?.entries || []);
    setIncomeForm(createEmptyIncomeForm(currentDate));
    setShowPrimaryIncomeForm(false);
    setShowAdditionalIncomeForm(false);
    setVariableCycleAmount('');
    setIncomeError('');
    setFlowStep(1);
    setIncomeFlow('primary');
  }, [isOpen, cash?.entries, currentDate]);

  const handleNumberChange = (setter) => (e) => {
    const value = e.target.value;
    const filtered = value.replace(/[^0-9.]/g, '');
    const parts = filtered.split('.');
    if (parts.length > 2) {
      setter(parts[0] + '.' + parts.slice(1).join(''));
    } else {
      setter(filtered);
    }
  };

  const monthCashSpent = (expenses || [])
    .filter((e) => {
      const expDate = new Date(e.date);
      const current = new Date(currentDate);
      return expDate.getMonth() === current.getMonth() && expDate.getFullYear() === current.getFullYear() && e.method === 'Cash';
    })
    .reduce((sum, e) => sum + e.amount, 0);

  const monthCardPaymentsTotal = getMonthlyCardPaymentsTotal(cash?.payments, currentDate);
  const currentMonthEntries = entries.filter((entry) => isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate));
  const previewPrimary = Number(primaryIncome) || 0;
  const autoDepositsForMonth = getAutoDepositsForMonth(entries, currentDate);
  const variableCycleEntriesForMonth = currentMonthEntries.filter((entry) => entry.type === 'primary-variable-cycle');
  const extrasForMonth = currentMonthEntries.filter((entry) => entry.type === 'extra' && !entry.autoGenerated);
  const principalIncome = getMonthlyIncomeContribution({ amount: previewPrimary, frequency: primaryFrequency, type: 'primary' });
  const depositedPrimaryIncome = [...autoDepositsForMonth, ...variableCycleEntriesForMonth].reduce((sum, entry) => sum + Number(entry.amount || 0), 0);
  const extraMonthIncome = extrasForMonth.reduce((sum, entry) => sum + getMonthlyIncomeContribution(entry), 0);
  const primaryFrequencyLabel = frequencyLabels[primaryFrequency] || 'Mensual';
  const previewPrimaryEntry = createPrimaryIncomeEntry(
    previewPrimary,
    currentDate,
    'Ingreso principal',
    primaryFrequency,
    primaryPayDate ? new Date(`${primaryPayDate}T12:00:00`).toISOString() : currentDate,
    primaryIncomeType
  );
  const variableCycleInfo = getPendingVariableCycleInfo(previewPrimaryEntry, entries, currentDate);
  const accruedCashIncome = depositedPrimaryIncome + extraMonthIncome;
  const cashAvailable = accruedCashIncome - monthCashSpent - monthCardPaymentsTotal;
  const incomeCount = [...autoDepositsForMonth, ...variableCycleEntriesForMonth, ...extrasForMonth].length;
  const sortedMonthEntries = [...currentMonthEntries]
    .filter((entry) => entry.type !== 'primary' || entry.autoGenerated || entry.type === 'primary-auto')
    .sort((a, b) => new Date(getIncomeEntryDate(b, currentDate)) - new Date(getIncomeEntryDate(a, currentDate)));

  const persistIncomeEntries = (updatedEntries) => {
    const updatedMonthIncome = updatedEntries
      .filter((entry) => isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate))
      .filter((entry) => entry.type !== 'primary' && !entry.isPrimaryConfig)
      .reduce((sum, entry) => sum + getMonthlyIncomeContribution(entry), 0);

    onUpdate({
      cash: {
        income: updatedMonthIncome,
        entries: updatedEntries,
        payments: cash?.payments || []
      }
    });
  };

  const openPrimaryIncomeForm = () => {
    setShowAdditionalIncomeForm(false);
    setShowPrimaryIncomeForm(true);
    setIncomeError('');
  };

  const openAdditionalIncomeForm = () => {
    setShowPrimaryIncomeForm(false);
    setShowAdditionalIncomeForm(true);
    setIncomeError('');
  };

  const handleIncomeFormChange = (field, value) => {
    const parsedValue = field === 'source' ? formatSourceText(sanitizeSourceInput(value)) : value;
    setIncomeForm((prev) => ({ ...prev, [field]: parsedValue }));
  };

  const handlePrimaryIncomeTypeChange = (nextType) => {
    setPrimaryIncomeType((previousType) => {
      if (previousType !== nextType && nextType === 'variable') {
        setPrimaryIncome('0');
        setVariableCycleAmount('');
      }
      return nextType;
    });
    setIncomeError('');
  };

  const handleAddIncomeEntry = () => {
    const amount = parseFloat(incomeForm.amount) || 0;
    const source = formatSourceText(incomeForm.source);
    if (amount <= 0) {
      setIncomeError('Debes indicar un monto válido para el ingreso.');
      return;
    }
    if (!source.trim()) {
      setIncomeError('Debes indicar de dónde proviene ese ingreso.');
      return;
    }

    const entryDate = incomeForm.date ? new Date(`${incomeForm.date}T12:00:00`).toISOString() : new Date().toISOString();
    const newEntry = {
      id: `income-${incomeForm.type}-${Date.now()}`,
      amount,
      source,
      type: incomeForm.type,
      frequency: 'one-time',
      date: entryDate,
      createdAt: entryDate
    };

    const updatedEntries = [...entries, newEntry];
    setEntries(updatedEntries);
    persistIncomeEntries(updatedEntries);
    setIncomeForm(createEmptyIncomeForm(currentDate));
    setIncomeError('');
    setShowAdditionalIncomeForm(false);
  };

  const handleRemoveIncomeEntry = (id) => {
    const updatedEntries = entries.filter((entry) => entry.id !== id);
    setEntries(updatedEntries);
    persistIncomeEntries(updatedEntries);
  };

  const handleCancelPrimaryIncome = () => {
    const freshPrimaryEntry = entries.find((entry) => entry.type === 'primary' || entry.isPrimaryConfig);
    setPrimaryIncome(freshPrimaryEntry?.amount?.toString() || '0');
    setPrimaryFrequency(freshPrimaryEntry?.frequency || 'monthly');
    setPrimaryIncomeType(freshPrimaryEntry?.incomeType || 'fixed');
    setPrimaryPayDate(getPrimaryAnchorDateValue(freshPrimaryEntry, currentDate));
    setIncomeError('');
    setShowPrimaryIncomeForm(false);
    setVariableCycleAmount('');
  };

  const savePrimaryIncomeConfig = ({ registerVariableCycle = false } = {}) => {
    const primaryAmount = parseFloat(primaryIncome) || 0;
    const primaryDate = currentDate;
    const normalizedAnchorDate = primaryPayDate ? new Date(`${primaryPayDate}T12:00:00`).toISOString() : currentDate;
    const shouldClearVariableCycles = primaryIncomeType === 'fixed';
    const preservedEntries = entries.filter((entry) => {
      if (entry.type === 'primary' || entry.isPrimaryConfig || entry.autoGenerated || entry.type === 'primary-auto') {
        return false;
      }

      if (shouldClearVariableCycles && entry.type === 'primary-variable-cycle' && isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate)) {
        return false;
      }

      return true;
    });

    const updatedPrimary = createPrimaryIncomeEntry(primaryAmount, primaryDate, 'Ingreso principal', primaryFrequency, normalizedAnchorDate, primaryIncomeType);
    const updatedEntries = [updatedPrimary, ...preservedEntries];

    if (registerVariableCycle && primaryIncomeType === 'variable' && variableCycleInfo?.isPending && (parseFloat(variableCycleAmount) || 0) > 0) {
      const entryDate = new Date(currentDate).toISOString();
      updatedEntries.push({
        id: `income-primary-variable-${Date.now()}`,
        amount: parseFloat(variableCycleAmount) || 0,
        source: 'Ingreso principal',
        type: 'primary-variable-cycle',
        frequency: 'one-time',
        date: entryDate,
        createdAt: entryDate,
        cycleAnchorDate: variableCycleInfo.cycleKey,
        incomeType: 'variable'
      });
    }

    onUpdate({
      cash: {
        income: updatedEntries
          .filter((entry) => isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate))
          .filter((entry) => entry.type !== 'primary' && !entry.isPrimaryConfig)
          .reduce((sum, entry) => sum + getMonthlyIncomeContribution(entry), 0),
        entries: updatedEntries,
        payments: cash?.payments || []
      },
    });

    setEntries(updatedEntries);
    setPrimarySaved(true);
    setShowPrimaryIncomeForm(false);
    setIncomeError('');
    setVariableCycleAmount('');
    setTimeout(() => setPrimarySaved(false), 2000);
  };

  const handleSavePrimaryIncome = () => {
    savePrimaryIncomeConfig();
  };

  const handleRegisterVariableCycle = () => {
    if (!variableCycleInfo?.isPending) {
      setIncomeError('Este ciclo ya fue registrado.');
      return;
    }
    const amount = parseFloat(variableCycleAmount) || 0;
    if (amount <= 0) {
      setIncomeError('Debes indicar el monto real cobrado en este ciclo.');
      return;
    }

    const entryDate = new Date(currentDate).toISOString();
    const newEntry = {
      id: `income-primary-variable-${Date.now()}`,
      amount,
      source: 'Ingreso principal',
      type: 'primary-variable-cycle',
      frequency: 'one-time',
      date: entryDate,
      createdAt: entryDate,
      cycleAnchorDate: variableCycleInfo.cycleKey,
      incomeType: 'variable'
    };

    const updatedEntries = [...entries, newEntry];
    setEntries(updatedEntries);
    persistIncomeEntries(updatedEntries);
    setVariableCycleAmount('');
    setIncomeError('');
  };


  const resetWizard = () => {
    setFlowStep(1);
    setIncomeFlow('primary');
    setIncomeError('');
    setVariableCycleAmount('');
    setIncomeForm(createEmptyIncomeForm(currentDate));
  };

  const handleClose = () => {
    resetWizard();
    onClose();
  };

  const handleSelectFlow = (nextFlow) => {
    setIncomeFlow(nextFlow);
    setFlowStep(2);
    setIncomeError('');
    if (nextFlow === 'additional') {
      setIncomeForm(createEmptyIncomeForm(currentDate));
    }
  };

  const canGoNext = () => {
    if (flowStep === 1) return Boolean(incomeFlow);
    if (incomeFlow === 'primary' && flowStep === 2) {
      return Boolean(primaryFrequency && primaryIncomeType && primaryPayDate);
    }
    if (incomeFlow === 'additional' && flowStep === 2) {
      return (parseFloat(incomeForm.amount) || 0) > 0 && Boolean(incomeForm.date);
    }
    return true;
  };

  const handleNextStep = () => {
    if (flowStep >= 3) return;
    if (!canGoNext()) {
      if (incomeFlow === 'primary') {
        setIncomeError('Completa la frecuencia, el tipo y la fecha del ingreso principal.');
      } else {
        setIncomeError('Completa el monto y la fecha antes de continuar.');
      }
      return;
    }
    setIncomeError('');
    setFlowStep((prev) => Math.min(prev + 1, 3));
  };

  const handlePreviousStep = () => {
    setIncomeError('');
    if (flowStep === 1) return;
    if (flowStep === 2) {
      setFlowStep(1);
      return;
    }
    setFlowStep(2);
  };

  const completePrimaryFlow = () => {
    if (!primaryFrequency || !primaryIncomeType || !primaryPayDate) {
      setIncomeError('Completa la configuración del ingreso principal.');
      return;
    }

    if (primaryIncomeType === 'fixed' && (parseFloat(primaryIncome) || 0) <= 0) {
      setIncomeError('Debes indicar un monto válido para el ingreso principal fijo.');
      return;
    }

    savePrimaryIncomeConfig({ registerVariableCycle: true });

    setTimeout(() => {
      handleClose();
    }, 250);
  };

  const completeAdditionalFlow = () => {
    const amount = parseFloat(incomeForm.amount) || 0;
    const source = formatSourceText(incomeForm.source);

    if (amount <= 0) {
      setIncomeError('Debes indicar un monto válido para el ingreso adicional.');
      return;
    }
    if (!source.trim()) {
      setIncomeError('Debes indicar de dónde proviene ese ingreso.');
      return;
    }

    handleAddIncomeEntry();
    setTimeout(() => {
      handleClose();
    }, 250);
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-stretch justify-stretch bg-[#F7F5F0] overflow-hidden"
          data-testid="income-modal"
        >
          <motion.div
            initial={{ y: '100%', opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: '100%', opacity: 0 }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
            className="w-full h-[100dvh] min-h-0 max-w-full bg-white overflow-hidden flex flex-col"
          >
            <div className="px-4 sm:px-5 py-4 sm:py-5 border-b border-[#E6E6E3] flex min-w-0 items-center justify-between gap-3 flex-shrink-0 bg-gradient-to-r from-[#FAFAF9] to-[#F5F4F1]">
              <div className="flex min-w-0 items-center gap-3">
                <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-[#2A7B5F] to-[#1F5E47] flex items-center justify-center shadow-lg shadow-[#2A7B5F]/20">
                  <Coins weight="fill" className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h2 className="font-heading font-semibold text-lg text-[#1A1C1A]">Nuevo ingreso</h2>
                  <p className="text-xs text-[#737573] font-medium">Paso {flowStep} de 3</p>
                </div>
              </div>
              <button
                onClick={handleClose}
                className="modal-close-btn"
                data-testid="close-income-modal"
              >
                <X weight="bold" />
              </button>
            </div>

            <div className="px-4 sm:px-5 py-3 flex gap-2 flex-shrink-0 bg-white">
              {[1, 2, 3].map((s) => (
                <div
                  key={s}
                  className={`flex-1 h-1.5 rounded-full transition-all duration-300 ${
                    s <= flowStep ? 'bg-gradient-to-r from-[#2A7B5F] to-[#1F5E47]' : 'bg-[#E6E6E3]'
                  }`}
                />
              ))}
            </div>

            <div className="flex-1 min-h-0 overflow-y-auto overscroll-contain px-4 sm:px-5 py-4 sm:py-5 bg-[#FAFAF9] space-y-5">
              <div className="w-full max-w-full min-w-0 overflow-hidden p-4 rounded-2xl bg-gradient-to-r from-[#F2F6F3] to-[#EEF4F0] border border-[#E6EDE8]">
                <div className="grid w-full min-w-0 grid-cols-1 min-[390px]:grid-cols-3 gap-3">
                  <div>
                    <p className="text-[11px] uppercase tracking-wider text-[#737573] font-semibold">Principal</p>
                    <p className="metric-value text-lg text-[#1E3A2B] mt-1">${formatMoney(principalIncome)}</p>
                    <p className="text-xs text-[#737573] mt-1">{primaryFrequencyLabel} · {primaryIncomeType === 'fixed' ? 'Fijo' : 'Variable'}</p>
                  </div>
                  <div>
                    <p className="text-[11px] uppercase tracking-wider text-[#737573] font-semibold">Extra</p>
                    <p className="metric-value text-lg text-[#1E3A2B] mt-1">${formatMoney(extraMonthIncome)}</p>
                    <p className="text-xs text-[#737573] mt-1">{extrasForMonth.length} movimiento(s)</p>
                  </div>
                  <div>
                    <p className="text-[11px] uppercase tracking-wider text-[#737573] font-semibold">Cash</p>
                    <p className="metric-value text-lg text-[#1E3A2B] mt-1">${formatMoney(cashAvailable)}</p>
                    <p className="text-xs text-[#737573] mt-1">{incomeCount} aplicado(s)</p>
                  </div>
                </div>
              </div>

              {incomeError && (
                <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="p-4 rounded-xl bg-[#9C382A]/10 border border-[#9C382A]/20">
                  <p className="text-sm text-[#9C382A] font-semibold">{incomeError}</p>
                </motion.div>
              )}

              <AnimatePresence mode="wait">
                {flowStep === 1 && (
                  <motion.div key="flow-step-1" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-4">
                    <div>
                      <label className="text-sm font-semibold text-[#1A1C1A] block mb-3">¿Qué quieres registrar?</label>
                      <div className="grid w-full min-w-0 grid-cols-1 sm:grid-cols-2 gap-4">
                        <button
                          type="button"
                          onClick={() => handleSelectFlow('primary')}
                          className={`p-5 rounded-2xl border-2 transition-all text-left ${
                            incomeFlow === 'primary' ? 'border-[#2A7B5F] bg-[#2A7B5F]/5 shadow-lg' : 'border-[#E6E6E3] hover:border-[#2A7B5F]/30 hover:shadow-md'
                          }`}
                        >
                          <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${incomeFlow === 'primary' ? 'bg-gradient-to-br from-[#2A7B5F] to-[#1F5E47]' : 'bg-[#F2F0EB]'}`}>
                            <Bank weight="fill" className={`w-5 h-5 ${incomeFlow === 'primary' ? 'text-white' : 'text-[#737573]'}`} />
                          </div>
                          <p className="font-semibold text-[#1A1C1A] text-lg">Ingreso principal</p>
                          <p className="text-sm text-[#737573] mt-1">Configura tu cobro base y deja sincronizado el cash del mes.</p>
                          <div className="mt-4 flex flex-wrap gap-2">
                            <span className="px-3 py-1.5 rounded-full bg-[#F2F0EB] text-xs font-semibold text-[#737573]">{primaryFrequencyLabel}</span>
                            <span className="px-3 py-1.5 rounded-full bg-[#F2F0EB] text-xs font-semibold text-[#737573]">{primaryIncomeType === 'fixed' ? 'Fijo' : 'Variable'}</span>
                          </div>
                        </button>

                        <button
                          type="button"
                          onClick={() => handleSelectFlow('additional')}
                          className={`p-5 rounded-2xl border-2 transition-all text-left ${
                            incomeFlow === 'additional' ? 'border-[#2A7B5F] bg-[#2A7B5F]/5 shadow-lg' : 'border-[#E6E6E3] hover:border-[#2A7B5F]/30 hover:shadow-md'
                          }`}
                        >
                          <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${incomeFlow === 'additional' ? 'bg-gradient-to-br from-[#2A7B5F] to-[#1F5E47]' : 'bg-[#F2F0EB]'}`}>
                            <Plus weight="bold" className={`w-5 h-5 ${incomeFlow === 'additional' ? 'text-white' : 'text-[#737573]'}`} />
                          </div>
                          <p className="font-semibold text-[#1A1C1A] text-lg">Ingreso adicional</p>
                          <p className="text-sm text-[#737573] mt-1">Registra trabajos extra, ventas, reembolsos o cualquier entrada puntual.</p>
                          <div className="mt-4 flex flex-wrap gap-2">
                            <span className="px-3 py-1.5 rounded-full bg-[#F2F0EB] text-xs font-semibold text-[#737573]">{extrasForMonth.length} este mes</span>
                            <span className="px-3 py-1.5 rounded-full bg-[#F2F0EB] text-xs font-semibold text-[#737573]">Un solo registro</span>
                          </div>
                        </button>
                      </div>
                    </div>

                    {sortedMonthEntries.length > 0 && (
                      <div className="p-4 rounded-2xl border border-[#E6E6E3] bg-white">
                        <p className="text-sm font-semibold text-[#1A1C1A] mb-3">Movimientos de ingreso recientes</p>
                        <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
                          {sortedMonthEntries.slice(0, 4).map((entry) => (
                            <div key={entry.id} className="flex items-center justify-between gap-3 p-3 rounded-xl bg-[#FAFAF9] border border-[#F0EEEA]">
                              <div className="min-w-0">
                                <p className="font-medium text-[#1A1C1A] truncate">{entry.source || 'Ingreso principal'}</p>
                                <p className="text-xs text-[#737573]">{new Date(getIncomeEntryDate(entry, currentDate)).toLocaleDateString('es-MX')} · {entry.type === 'primary-variable-cycle' ? 'Ciclo variable' : entry.type === 'extra' ? 'Ingreso extra' : 'Principal'}</p>
                              </div>
                              <span className="metric-value text-sm text-[#1E3A2B]">${formatMoney(entry.amount)}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </motion.div>
                )}

                {flowStep === 2 && incomeFlow === 'primary' && (
                  <motion.div key="flow-step-2-primary" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-5">
                    <div>
                      <label className="text-sm font-semibold text-[#1A1C1A] block mb-3">¿Cada cuánto cobras?</label>
                      <div className="grid w-full min-w-0 grid-cols-1 sm:grid-cols-3 gap-3">
                        {incomeFrequencyOptions.map((option) => {
                          const isActive = primaryFrequency === option.value;
                          return (
                            <button
                              key={option.value}
                              type="button"
                              onClick={() => setPrimaryFrequency(option.value)}
                              className={`p-4 rounded-xl border-2 transition-all ${isActive ? 'border-[#2A7B5F] bg-[#2A7B5F]/5 shadow-md' : 'border-[#E6E6E3] hover:border-[#2A7B5F]/30'}`}
                            >
                              <span className={`font-semibold ${isActive ? 'text-[#1E3A2B]' : 'text-[#737573]'}`}>{option.label}</span>
                            </button>
                          );
                        })}
                      </div>
                    </div>

                    <div>
                      <label className="text-sm font-semibold text-[#1A1C1A] block mb-3">Tipo de ingreso</label>
                      <div className="grid w-full min-w-0 grid-cols-1 sm:grid-cols-2 gap-3">
                        {[
                          { value: 'fixed', title: 'Fijo', desc: 'Siempre cobras el mismo monto.' },
                          { value: 'variable', title: 'Variable', desc: 'El monto cambia en cada ciclo.' },
                        ].map((option) => {
                          const isActive = primaryIncomeType === option.value;
                          return (
                            <button
                              key={option.value}
                              type="button"
                              onClick={() => handlePrimaryIncomeTypeChange(option.value)}
                              className={`p-4 rounded-xl border-2 transition-all text-left ${isActive ? 'border-[#2A7B5F] bg-[#2A7B5F]/5 shadow-md' : 'border-[#E6E6E3] hover:border-[#2A7B5F]/30'}`}
                            >
                              <p className={`font-semibold ${isActive ? 'text-[#1E3A2B]' : 'text-[#1A1C1A]'}`}>{option.title}</p>
                              <p className="text-sm text-[#737573] mt-1">{option.desc}</p>
                            </button>
                          );
                        })}
                      </div>
                    </div>

                    <div>
                      <label className="text-sm font-semibold text-[#1A1C1A] block mb-2">Fecha base del cobro</label>
                      <input
                        type="date"
                        value={primaryPayDate}
                        onChange={(e) => setPrimaryPayDate(e.target.value)}
                        className="premium-input mobile-date-input"
                      />
                      <p className="text-xs text-[#737573] mt-1.5">La app usa esta fecha para calcular tus ciclos automáticos.</p>
                    </div>
                  </motion.div>
                )}

                {flowStep === 2 && incomeFlow === 'additional' && (
                  <motion.div key="flow-step-2-additional" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-5">
                    <div>
                      <label className="text-sm font-semibold text-[#1A1C1A] block mb-2">¿Cuánto te entró?</label>
                      <div className="relative">
                        <input
                          type="text"
                          inputMode="decimal"
                          value={incomeForm.amount}
                          onChange={handleNumberChange((value) => handleIncomeFormChange('amount', value))}
                          placeholder="0.00"
                          className="premium-input px-4 text-xl sm:text-2xl font-mono"
                        />
                      </div>
                    </div>

                    <div>
                      <label className="text-sm font-semibold text-[#1A1C1A] block mb-2">Fecha del ingreso</label>
                      <input
                        type="date"
                        value={incomeForm.date}
                        onChange={(e) => handleIncomeFormChange('date', e.target.value)}
                        className="premium-input mobile-date-input"
                      />
                    </div>

                    <div className="p-4 rounded-xl bg-gradient-to-r from-[#F2F0EB] to-[#EAE8E3]">
                      <p className="text-xs font-semibold text-[#737573] uppercase tracking-wider mb-2">Vista previa</p>
                      <div className="flex items-center justify-between gap-3 flex-wrap">
                        <span className="text-sm text-[#737573]">Se sumará al cash del mes como ingreso extra</span>
                        <span className="metric-value text-base text-[#1E3A2B]">${formatMoney(incomeForm.amount || 0)}</span>
                      </div>
                    </div>
                  </motion.div>
                )}

                {flowStep === 3 && incomeFlow === 'primary' && (
                  <motion.div key="flow-step-3-primary" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-5">
                    {primaryIncomeType === 'fixed' ? (
                      <div>
                        <label className="text-sm font-semibold text-[#1A1C1A] block mb-2">Monto por cobro</label>
                        <div className="relative">
                            <input
                            type="text"
                            inputMode="decimal"
                            value={primaryIncome}
                            onChange={handleNumberChange(setPrimaryIncome)}
                            placeholder="0.00"
                            className="premium-input px-4 text-xl sm:text-2xl font-mono"
                          />
                        </div>
                        <p className="text-xs text-[#737573] mt-1.5">Estimado mensual: ${formatMoney(principalIncome)}</p>
                      </div>
                    ) : (
                      <div className="p-4 rounded-2xl border border-[#E6E6E3] bg-white space-y-3">
                        <div>
                          <p className="text-sm font-semibold text-[#1A1C1A]">Ingreso principal variable</p>
                          <p className="text-sm text-[#737573] mt-1">La estructura queda guardada y luego registras el monto real cobrado en cada ciclo.</p>
                        </div>
                        {variableCycleInfo?.isPending ? (
                          <>
                            <div className="p-3 rounded-xl bg-[#F4C27A]/12 border border-[#F4C27A]/25">
                              <p className="text-sm font-semibold text-[#8A5A15]">Ciclo pendiente por registrar</p>
                              <p className="text-xs text-[#8A5A15]/80 mt-1">Si ya cobraste este ciclo, puedes dejarlo registrado ahora.</p>
                            </div>
                            <div>
                              <label className="text-sm font-semibold text-[#1A1C1A] block mb-2">Monto real de este ciclo (opcional)</label>
                              <div className="relative">
                                        <input
                                  type="text"
                                  inputMode="decimal"
                                  value={variableCycleAmount}
                                  onChange={handleNumberChange(setVariableCycleAmount)}
                                  placeholder="0.00"
                                  className="premium-input px-4 text-xl sm:text-2xl font-mono"
                                />
                              </div>
                            </div>
                          </>
                        ) : (
                          <div className="p-3 rounded-xl bg-[#2A7B5F]/8 border border-[#2A7B5F]/15 flex items-center gap-2">
                            <Check weight="bold" className="w-4 h-4 text-[#2A7B5F]" />
                            <p className="text-sm text-[#1E3A2B] font-medium">Este ciclo ya está registrado.</p>
                          </div>
                        )}
                      </div>
                    )}

                    <div className="p-4 rounded-2xl border border-[#E6E6E3] bg-white">
                      <p className="text-sm font-semibold text-[#1A1C1A] mb-3">Resumen</p>
                      <div className="space-y-2 text-sm text-[#737573]">
                        <div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><span>Frecuencia</span><span className="font-semibold text-[#1A1C1A]">{primaryFrequencyLabel}</span></div>
                        <div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><span>Tipo</span><span className="font-semibold text-[#1A1C1A]">{primaryIncomeType === 'fixed' ? 'Fijo' : 'Variable'}</span></div>
                        <div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><span>Fecha base</span><span className="font-semibold text-[#1A1C1A]">{new Date(`${primaryPayDate}T12:00:00`).toLocaleDateString('es-MX')}</span></div>
                        <div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><span>Impacto mensual</span><span className="font-semibold text-[#1E3A2B]">${formatMoney(principalIncome)}</span></div>
                      </div>
                    </div>
                  </motion.div>
                )}

                {flowStep === 3 && incomeFlow === 'additional' && (
                  <motion.div key="flow-step-3-additional" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="space-y-5">
                    <div>
                      <label className="text-sm font-semibold text-[#1A1C1A] block mb-2">¿De dónde proviene?</label>
                      <input
                        type="text"
                        value={incomeForm.source}
                        onChange={(e) => handleIncomeFormChange('source', e.target.value)}
                        placeholder="Ej: Trabajo, venta, reembolso, Uber"
                        className="premium-input text-base sm:text-lg"
                        autoComplete="off"
                      />
                      <p className="text-xs text-[#737573] mt-1.5">Solo letras. La primera palabra quedará con mayúscula.</p>
                    </div>

                    <div className="p-4 rounded-2xl border border-[#E6E6E3] bg-white">
                      <p className="text-sm font-semibold text-[#1A1C1A] mb-3">Resumen</p>
                      <div className="space-y-2 text-sm text-[#737573]">
                        <div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><span>Monto</span><span className="font-semibold text-[#1E3A2B]">${formatMoney(incomeForm.amount || 0)}</span></div>
                        <div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><span>Fecha</span><span className="font-semibold text-[#1A1C1A]">{incomeForm.date ? new Date(`${incomeForm.date}T12:00:00`).toLocaleDateString('es-MX') : '—'}</span></div>
                        <div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><span>Origen</span><span className="font-semibold text-[#1A1C1A]">{incomeForm.source || 'Pendiente'}</span></div>
                      </div>
                    </div>

                    <div className="flex items-start gap-3 p-3 rounded-xl bg-[#F2F6F3] border border-[#E6EDE8]">
                      <Info weight="fill" className="w-5 h-5 text-[#2A7B5F] flex-shrink-0 mt-0.5" />
                      <p className="text-sm text-[#49635A]">Este ingreso se agrega como movimiento extra del mes y se sincroniza con el cash disponible.</p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            <div className="px-4 sm:px-5 py-4 sm:py-5 border-t border-[#E6E6E3] bg-white flex flex-col-reverse sm:flex-row gap-3 flex-shrink-0 pb-[calc(1rem+env(safe-area-inset-bottom,0px))]">
              {flowStep > 1 ? (
                <button onClick={handlePreviousStep} className="flex-1 w-full btn-modal-secondary">
                  Atrás
                </button>
              ) : (
                <button onClick={handleClose} className="flex-1 w-full btn-modal-secondary">
                  Cerrar
                </button>
              )}

              {flowStep < 3 ? (
                <button
                  onClick={handleNextStep}
                  disabled={!canGoNext() && flowStep !== 1}
                  className={`flex-1 w-full btn-modal-primary ${!canGoNext() && flowStep !== 1 ? 'opacity-50 cursor-not-allowed' : ''}`}
                >
                  Continuar
                </button>
              ) : (
                <button
                  onClick={incomeFlow === 'primary' ? completePrimaryFlow : completeAdditionalFlow}
                  className="flex-1 w-full btn-modal-primary"
                >
                  {incomeFlow === 'primary' ? (primarySaved ? 'Ingreso guardado' : 'Guardar ingreso') : 'Guardar ingreso'}
                </button>
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

