import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Wallet } from '@phosphor-icons/react';
import LoginScreen from './components/LoginScreen';
import Layout from './components/Layout';
import Dashboard from './components/Dashboard';
import ExpensesList from './components/ExpensesList';
import CardsPanel from './components/CardsPanel';
import CalendarView from './components/CalendarView';
import Statistics from './components/Statistics';
import Settings from './components/Settings';
import ExpenseModal from './components/ExpenseModal';
import IncomeModal from './components/IncomeModal';
import './App.css';
import { isFirebaseConfigured, loadCloudData, saveCloudData, signInWithProvider, signOutUser, subscribeToAuth } from './lib/firebase';
import { getEmailSession, verifyEmailCode, loginWithPassword, loadUserCloudData, saveUserCloudData } from './lib/emailAuth';
import { migrateLegacyDates, toDateOnlyString, parseDateOnly } from './lib/dateUtils';

const STORAGE_KEY = 'gastospro-data';

const getScopedStorageKey = (session = null) => {
  if (!session) return STORAGE_KEY;
  if (['email-otp', 'email-password'].includes(session.provider) && session.email) {
    return `${STORAGE_KEY}::${session.email.toLowerCase()}`;
  }
  if (session.provider === 'guest') return `${STORAGE_KEY}::guest`;
  return STORAGE_KEY;
};

const loadLocalDataForSession = (session = null) => {
  const saved = localStorage.getItem(getScopedStorageKey(session));
  if (saved) {
    try {
      return normalizeData(JSON.parse(saved));
    } catch {}
  }
  return normalizeData({
    cash: { income: 0, entries: [createPrimaryIncomeEntry(0)], savings: { entries: [] } },
    expenses: [],
    cards: [],
    goals: { type: 'weekly', amount: 0 },
    currentDate: new Date().toISOString()
  });
};

const getIncomeEntryDate = (entry, fallbackDate = new Date().toISOString()) => (
  entry?.date || entry?.createdAt || fallbackDate
);

const isSameMonth = (dateA, dateB) => {
  const a = new Date(dateA);
  const b = new Date(dateB);
  return a.getMonth() === b.getMonth() && a.getFullYear() === b.getFullYear();
};

const createPrimaryIncomeEntry = (amount, date = new Date().toISOString(), source = 'Ingreso principal', frequency = 'monthly', anchorDate = null, incomeType = 'fixed') => ({
  id: 'income-primary-config',
  amount: Number(amount || 0),
  source,
  type: 'primary',
  frequency,
  date,
  anchorDate: anchorDate || date,
  isPrimaryConfig: true,
  incomeType: incomeType,
  createdAt: date
});

const getRecurrenceStepDays = (frequency = 'monthly') => {
  if (frequency === 'weekly') return 7;
  if (frequency === 'biweekly') return 14;
  return null;
};

const generatePrimaryAutoEntries = (primaryConfig, currentDate) => {
  if (!primaryConfig || Number(primaryConfig.amount || 0) <= 0) return [];
  if ((primaryConfig.incomeType || 'fixed') === 'variable') return [];

  const current = new Date(currentDate);
  const start = new Date(primaryConfig.anchorDate || primaryConfig.date || currentDate);
  start.setHours(12, 0, 0, 0);
  current.setHours(23, 59, 59, 999);

  if (Number.isNaN(start.getTime()) || start > current) return [];

  const entries = [];
  const frequency = primaryConfig.frequency || 'monthly';
  const stepDays = getRecurrenceStepDays(frequency);
  const cursor = new Date(start);

  while (cursor <= current) {
    if (cursor.getMonth() === current.getMonth() && cursor.getFullYear() === current.getFullYear()) {
      const iso = new Date(cursor).toISOString();
      entries.push({
        id: `income-primary-auto-${cursor.getFullYear()}-${cursor.getMonth() + 1}-${cursor.getDate()}`,
        amount: Number(primaryConfig.amount || 0),
        source: primaryConfig.source || 'Ingreso principal',
        type: 'primary-auto',
        frequency: 'one-time',
        date: iso,
        createdAt: iso,
        autoGenerated: true,
        relatedPrimaryId: primaryConfig.id || 'income-primary-config',
        incomeType: 'fixed'
      });
    }

    if (frequency === 'monthly') {
      cursor.setMonth(cursor.getMonth() + 1);
    } else if (stepDays) {
      cursor.setDate(cursor.getDate() + stepDays);
    } else {
      break;
    }
  }

  return entries;
};

const getMonthlyIncomeContribution = (entry) => {
  const amount = Number(entry?.amount || 0);

  if (entry?.autoGenerated || entry?.type === 'primary-auto') {
    return amount;
  }

  const frequency = entry?.frequency || (entry?.type === 'primary' ? 'monthly' : 'one-time');

  if (frequency === 'weekly') return amount * 4.33;
  if (frequency === 'biweekly') return amount * 2;
  return amount;
};

const getCardPaymentDate = (payment, fallbackDate = new Date().toISOString()) => (
  payment?.date || payment?.createdAt || fallbackDate
);

const getMonthlyCardPaymentsTotal = (payments = [], currentDate = new Date().toISOString()) => (
  payments
    .filter((payment) => isSameMonth(getCardPaymentDate(payment, currentDate), currentDate))
    .reduce((sum, payment) => sum + Number(payment.amount || 0), 0)
);


const normalizeSavings = (savings = {}) => {
  const entries = (Array.isArray(savings.entries) ? savings.entries : []).map((entry) => ({
    id: entry.id || `saving-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    type: entry.type === 'withdraw' ? 'withdraw' : 'deposit',
    amount: Math.max(0, Number(entry.amount || 0)),
    purpose: entry.purpose || 'general',
    cardId: entry.cardId || null,
    cardName: entry.cardName || '',
    note: entry.note || '',
    date: entry.date || entry.createdAt || new Date().toISOString(),
    createdAt: entry.createdAt || entry.date || new Date().toISOString()
  })).filter((entry) => entry.amount > 0);

  return { entries };
};

const getSavingsBalance = (cash = {}) => (
  (cash?.savings?.entries || []).reduce((sum, entry) => (
    sum + (entry.type === 'withdraw' ? -Number(entry.amount || 0) : Number(entry.amount || 0))
  ), 0)
);

const normalizeCash = (cash = {}, currentDate = new Date().toISOString()) => {
  const entries = (Array.isArray(cash.entries) ? cash.entries : []).map((entry) => {
    const entryDate = getIncomeEntryDate(entry, currentDate);
    return {
      ...entry,
      amount: Number(entry.amount || 0),
      source: entry.source || ((entry.type === 'primary' || entry.isPrimaryConfig) ? 'Ingreso principal' : 'Ingreso adicional'),
      type: entry.type || 'extra',
      frequency: entry.frequency || ((entry.type === 'primary' || entry.isPrimaryConfig) ? 'monthly' : 'one-time'),
      date: entryDate,
      anchorDate: entry.anchorDate || entryDate,
      isPrimaryConfig: Boolean(entry.isPrimaryConfig || entry.type === 'primary'),
      autoGenerated: Boolean(entry.autoGenerated || entry.type === 'primary-auto'),
      incomeType: entry.incomeType || 'fixed',
      createdAt: entry.createdAt || entryDate
    };
  });

  const manualEntries = entries.filter((entry) => !entry.autoGenerated && entry.type !== 'primary-auto');
  const primaryConfigs = manualEntries.filter((entry) => entry.type === 'primary' || entry.isPrimaryConfig);
  const sortedPrimaryConfigs = [...primaryConfigs].sort((a, b) => new Date(b.anchorDate || b.date || currentDate) - new Date(a.anchorDate || a.date || currentDate));
  const primaryConfig = sortedPrimaryConfigs[0] || createPrimaryIncomeEntry(Number(cash.income || 0), currentDate);

  const nonPrimaryManualEntries = manualEntries.filter((entry) => !(entry.type === 'primary' || entry.isPrimaryConfig));
  const regeneratedAutoEntries = generatePrimaryAutoEntries(primaryConfig, currentDate);
  const normalizedEntries = [primaryConfig, ...nonPrimaryManualEntries, ...regeneratedAutoEntries];

  const currentMonthEntries = normalizedEntries.filter((entry) => isSameMonth(getIncomeEntryDate(entry, currentDate), currentDate));
  const income = currentMonthEntries
    .filter((entry) => entry.type !== 'primary' && !entry.isPrimaryConfig)
    .reduce((sum, entry) => sum + getMonthlyIncomeContribution(entry), 0);
  const payments = (Array.isArray(cash.payments) ? cash.payments : []).map((payment) => {
    const paymentDate = getCardPaymentDate(payment, currentDate);
    return {
      ...payment,
      amount: Number(payment.amount || 0),
      cardId: payment.cardId || null,
      cardName: payment.cardName || 'Tarjeta',
      date: paymentDate,
      createdAt: payment.createdAt || paymentDate
    };
  });

  return {
    income,
    entries: normalizedEntries,
    payments,
    savings: normalizeSavings(cash.savings)
  };
};

const normalizeData = (rawData) => {
  // Migración de fechas legacy: convierte cualquier paymentDate o expense.date
  // que esté guardado como ISO con timezone a "YYYY-MM-DD" puro.
  // Es idempotente — los datos ya correctos no se tocan. Corre en cada
  // carga (local y cloud) para que la corrección llegue a todos los datos.
  const migrated = migrateLegacyDates(rawData);

  const baseDate = migrated?.currentDate || new Date().toISOString();
  const baseData = migrated || {
    cash: { income: 0, entries: [createPrimaryIncomeEntry(0, baseDate)], savings: { entries: [] } },
    expenses: [],
    cards: [],
    goals: { type: 'weekly', amount: 0 },
    currentDate: baseDate
  };

  return {
    ...baseData,
    cash: normalizeCash(baseData.cash, baseDate),
    expenses: Array.isArray(baseData.expenses) ? baseData.expenses : [],
    cards: Array.isArray(baseData.cards) ? baseData.cards : [],
    goals: baseData.goals || { type: 'weekly', amount: 0 },
    currentDate: baseDate
  };
};

const getInitialData = () => loadLocalDataForSession(null);

const applyCardUsageDelta = (cards, cardId, delta) => (
  cards.map((card) => {
    if (card.id !== cardId) return card;
    return {
      ...card,
      used: Math.max(0, Number(card.used || 0) + delta)
    };
  })
);

const createEditEntry = (previousExpense, nextExpense) => ({
  editedAt: new Date().toISOString(),
  previousAmount: previousExpense.amount,
  newAmount: nextExpense.amount,
  previousMethod: previousExpense.method,
  newMethod: nextExpense.method,
  previousCardId: previousExpense.cardId || null,
  newCardId: nextExpense.cardId || null,
  previousName: previousExpense.name,
  newName: nextExpense.name,
  previousCategory: previousExpense.category,
  newCategory: nextExpense.category
});

const didExpenseChange = (previousExpense, nextExpense) => (
  previousExpense.name !== nextExpense.name ||
  previousExpense.amount !== nextExpense.amount ||
  previousExpense.category !== nextExpense.category ||
  previousExpense.method !== nextExpense.method ||
  (previousExpense.cardId || null) !== (nextExpense.cardId || null)
);

function App() {
  const [activeTab, setActiveTab] = useState('home');
  const [showExpenseModal, setShowExpenseModal] = useState(false);
  const [showIncomeModal, setShowIncomeModal] = useState(false);
  const [editingExpense, setEditingExpense] = useState(null);
  const [data, setData] = useState(getInitialData);
  const [session, setSession] = useState(() => {
    const savedSession = localStorage.getItem('gastospro-session');
    return savedSession ? JSON.parse(savedSession) : null;
  });
  const [authUser, setAuthUser] = useState(null);
  const [authReady, setAuthReady] = useState(false);
  const [isEnteringApp, setIsEnteringApp] = useState(false);
  const [loginError, setLoginError] = useState('');
  const [isLoggingOut, setIsLoggingOut] = useState(false);
  const [logoutStage, setLogoutStage] = useState('idle');
  const isHydratingCloudRef = useRef(false);
  const cloudSaveTimeoutRef = useRef(null);
  const logoutTimeoutsRef = useRef([]);
  useEffect(() => {
    if (!session || ['google', 'apple'].includes(session.provider)) return;
    localStorage.setItem(getScopedStorageKey(session), JSON.stringify(data));
  }, [data, session]);

  useEffect(() => {
    const unsubscribe = subscribeToAuth(async (user) => {
      setAuthUser(user);

      if (user) {
        const providerId = user.providerData?.[0]?.providerId || 'google.com';
        const provider = providerId.includes('apple') ? 'apple' : 'google';
        const nextSession = {
          provider,
          uid: user.uid,
          email: user.email || '',
          name: user.displayName || user.email || 'Usuario',
          avatar: user.photoURL || '',
          enteredAt: new Date().toISOString(),
        };

        setSession((prev) => prev?.uid === user.uid && prev?.provider === provider ? prev : nextSession);

        try {
          isHydratingCloudRef.current = true;
          const cloudPayload = await loadCloudData(user.uid);
          if (cloudPayload) {
            setData(normalizeData(cloudPayload));
          }
        } catch (error) {
          console.error('Error loading cloud data:', error);
        } finally {
          isHydratingCloudRef.current = false;
          setAuthReady(true);
        }

        return;
      }

      const savedSession = localStorage.getItem('gastospro-session');
      const parsedSession = savedSession ? JSON.parse(savedSession) : null;
      if (parsedSession?.provider && ['google', 'apple'].includes(parsedSession.provider)) {
        setSession(null);
      }
      setAuthReady(true);
    });

    return () => unsubscribe?.();
  }, []);

  useEffect(() => {
    if (!authReady || !authUser || !session || !['google', 'apple'].includes(session.provider) || isHydratingCloudRef.current) return undefined;

    if (cloudSaveTimeoutRef.current) {
      window.clearTimeout(cloudSaveTimeoutRef.current);
    }

    cloudSaveTimeoutRef.current = window.setTimeout(() => {
      saveCloudData(authUser.uid, data).catch((error) => {
        console.error('Error saving cloud data:', error);
      });
    }, 600);

    return () => {
      if (cloudSaveTimeoutRef.current) {
        window.clearTimeout(cloudSaveTimeoutRef.current);
      }
    };
  }, [authReady, authUser, data, session]);

  useEffect(() => {
    if (!authReady || !session?.token || !['email-otp', 'email-password'].includes(session.provider) || isHydratingCloudRef.current) return undefined;

    if (cloudSaveTimeoutRef.current) {
      window.clearTimeout(cloudSaveTimeoutRef.current);
    }

    cloudSaveTimeoutRef.current = window.setTimeout(() => {
      saveUserCloudData(session.token, data).catch((error) => {
        console.error('Error saving Supabase cloud data:', error);
      });
    }, 700);

    return () => {
      if (cloudSaveTimeoutRef.current) {
        window.clearTimeout(cloudSaveTimeoutRef.current);
      }
    };
  }, [authReady, data, session?.token, session?.provider]);

  useEffect(() => {
    if (session) {
      localStorage.setItem('gastospro-session', JSON.stringify(session));
      return;
    }

    localStorage.removeItem('gastospro-session');
  }, [session]);

  useEffect(() => {
    if (!session || ['google', 'apple'].includes(session.provider)) return;

    if (session?.token && ['email-otp', 'email-password'].includes(session.provider)) {
      isHydratingCloudRef.current = true;
      loadUserCloudData(session.token)
        .then((cloudResponse) => {
          if (cloudResponse?.payload) {
            setData(normalizeData(cloudResponse.payload));
          } else {
            setData(loadLocalDataForSession(session));
          }
        })
        .catch((error) => {
          console.error('Error restoring Supabase cloud data:', error);
          setData(loadLocalDataForSession(session));
        })
        .finally(() => {
          window.setTimeout(() => {
            isHydratingCloudRef.current = false;
          }, 0);
        });
      return;
    }

    setData(loadLocalDataForSession(session));
  }, [session?.provider, session?.email, session?.token]);

  useEffect(() => {
    setData((prev) => normalizeData({ ...prev, currentDate: new Date().toISOString() }));
  }, []);

  useEffect(() => () => {
    logoutTimeoutsRef.current.forEach((timeoutId) => window.clearTimeout(timeoutId));
    logoutTimeoutsRef.current = [];
  }, []);

  const scheduleLogoutStep = (callback, delay) => {
    const timeoutId = window.setTimeout(callback, delay);
    logoutTimeoutsRef.current.push(timeoutId);
    return timeoutId;
  };

  const renderLogoutTransition = () => (
    <AnimatePresence>
      {isLoggingOut && (
        <motion.div
          key="logout-transition"
          initial={false}
          animate={{ opacity: logoutStage === 'reveal' ? 0 : 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: logoutStage === 'reveal' ? 0.8 : 0.35, ease: 'easeInOut' }}
          className={`logout-poweroff logout-poweroff--${logoutStage}`}
        >
          <div className="logout-poweroff__noise" />
          <div className="logout-poweroff__vignette" />
          <div className="logout-poweroff__glow" />
          <div className="logout-poweroff__top" />
          <div className="logout-poweroff__bottom" />
          <div className="logout-poweroff__flash" />
          <div className="logout-poweroff__line" />
          <div className="logout-poweroff__status">Cerrando sesión</div>
        </motion.div>
      )}
    </AnimatePresence>
  );


  const startSessionEntry = (payload) => {
    setIsEnteringApp(true);
    setLoginError('');

    window.setTimeout(() => {
      setSession(payload);
      setActiveTab('home');
      setIsEnteringApp(false);
    }, 240);
  };

  const handleGuestAccess = () => {
    setIsEnteringApp(true);
    setLoginError('');

    window.setTimeout(() => {
      setSession({
        provider: 'guest',
        enteredAt: new Date().toISOString(),
        name: 'Invitado'
      });
      setActiveTab('home');
      setIsEnteringApp(false);
    }, 5000);
  };

  const handleProviderSelect = async (provider) => {
    try {
      setLoginError('');
      setIsEnteringApp(true);
      const user = await signInWithProvider(provider);
      const baseSession = {
        provider,
        uid: user.uid,
        email: user.email || '',
        name: user.displayName || user.email || 'Usuario',
        avatar: user.photoURL || '',
        enteredAt: new Date().toISOString()
      };

      const cloudPayload = await loadCloudData(user.uid);
      if (cloudPayload) {
        isHydratingCloudRef.current = true;
        setData(normalizeData(cloudPayload));
        window.setTimeout(() => {
          isHydratingCloudRef.current = false;
        }, 0);
      }

      startSessionEntry(baseSession);
    } catch (error) {
      console.error('Login error:', error);
      setIsEnteringApp(false);
      setLoginError(error?.message || 'No se pudo completar el inicio de sesión.');
    }
  };

  const handleEmailCodeVerify = async ({ email, code }) => {
    try {
      setLoginError('');
      setIsEnteringApp(true);

      const verification = await verifyEmailCode(email, code);

      try {
        isHydratingCloudRef.current = true;
        const cloudResponse = await loadUserCloudData(verification.token);
        if (cloudResponse?.payload) {
          setData(normalizeData(cloudResponse.payload));
        } else {
          setData(loadLocalDataForSession({ provider: 'email-otp', email: verification.email }));
        }
      } catch (cloudError) {
        console.error('Error loading Supabase cloud data:', cloudError);
        setData(loadLocalDataForSession({ provider: 'email-otp', email: verification.email }));
      } finally {
        window.setTimeout(() => {
          isHydratingCloudRef.current = false;
        }, 0);
      }

      startSessionEntry({
        provider: 'email-otp',
        uid: verification.email,
        email: verification.email,
        name: verification.name || verification.email || 'Usuario',
        token: verification.token,
        isAdmin: Boolean(verification.is_admin),
        expiresAt: verification.expires_at || null,
        enteredAt: new Date().toISOString()
      });
    } catch (error) {
      console.error('OTP login error:', error);
      setIsEnteringApp(false);
      setLoginError(error?.message || 'No se pudo validar el código.');
      throw error;
    }
  };


  const handleDirectAdminLogin = async ({ email, password }) => {
    try {
      setLoginError('');
      setIsEnteringApp(true);

      const verification = await loginWithPassword(email, password);

      try {
        isHydratingCloudRef.current = true;
        const cloudResponse = await loadUserCloudData(verification.token);
        if (cloudResponse?.payload) {
          setData(normalizeData(cloudResponse.payload));
        } else {
          setData(loadLocalDataForSession({ provider: 'email-password', email: verification.email }));
        }
      } catch (cloudError) {
        console.error('Error loading Supabase cloud data:', cloudError);
        setData(loadLocalDataForSession({ provider: 'email-password', email: verification.email }));
      } finally {
        window.setTimeout(() => {
          isHydratingCloudRef.current = false;
        }, 0);
      }

      startSessionEntry({
        provider: 'email-password',
        uid: verification.email,
        email: verification.email,
        name: verification.name || verification.email || 'Administrador',
        token: verification.token,
        isAdmin: Boolean(verification.is_admin),
        expiresAt: verification.expires_at || null,
        enteredAt: new Date().toISOString()
      });
    } catch (error) {
      console.error('Password login error:', error);
      setIsEnteringApp(false);
      setLoginError(error?.message || 'No se pudo iniciar sesión con esa clave.');
      throw error;
    }
  };

  const handleLogout = async () => {
    if (isLoggingOut) return;

    logoutTimeoutsRef.current.forEach((timeoutId) => window.clearTimeout(timeoutId));
    logoutTimeoutsRef.current = [];

    setIsLoggingOut(true);
    setLogoutStage('turnoff');

    scheduleLogoutStep(async () => {
      try {
        if (['google', 'apple'].includes(session?.provider)) {
          await signOutUser();
        }
      } catch (error) {
        console.error('Logout error:', error);
      } finally {
        setActiveTab('home');
        setSession(null);
        setAuthUser(null);
        setLoginError('');
        setLogoutStage('reveal');
      }
    }, 1500);

    scheduleLogoutStep(() => {
      setIsLoggingOut(false);
      setLogoutStage('idle');
      logoutTimeoutsRef.current = [];
    }, 3000);
  };


  const addExpense = (expense) => {
    const normalizedAmount = Number(expense.amount);
    const expenseId = expense.id || Date.now().toString();

    setData((prev) => {
      const existingExpense = prev.expenses.find((item) => item.id === expenseId);
      let updatedCards = [...prev.cards];
      let updatedExpenses = [...prev.expenses];

      if (existingExpense) {
        if (existingExpense.method === 'Tarjeta' && existingExpense.cardId) {
          updatedCards = applyCardUsageDelta(updatedCards, existingExpense.cardId, -Number(existingExpense.amount));
        }

        const nextExpenseBase = {
          ...existingExpense,
          ...expense,
          id: existingExpense.id,
          amount: normalizedAmount,
          date: existingExpense.date,
          updatedAt: new Date().toISOString()
        };

        const expenseChanged = didExpenseChange(existingExpense, nextExpenseBase);
        const nextExpense = expenseChanged
          ? {
              ...nextExpenseBase,
              isEdited: true,
              editHistory: [
                ...(existingExpense.editHistory || []),
                createEditEntry(existingExpense, nextExpenseBase)
              ]
            }
          : {
              ...nextExpenseBase,
              isEdited: existingExpense.isEdited || false,
              editHistory: existingExpense.editHistory || []
            };

        if (nextExpense.method === 'Tarjeta' && nextExpense.cardId) {
          updatedCards = applyCardUsageDelta(updatedCards, nextExpense.cardId, normalizedAmount);
        }

        updatedExpenses = updatedExpenses.map((item) => (
          item.id === existingExpense.id ? nextExpense : item
        ));
      } else {
        const newExpense = {
          ...expense,
          id: expenseId,
          amount: normalizedAmount,
          createdAt: new Date().toISOString(),
          isEdited: false,
          editHistory: []
        };

        if (newExpense.method === 'Tarjeta' && newExpense.cardId) {
          updatedCards = applyCardUsageDelta(updatedCards, newExpense.cardId, normalizedAmount);
        }

        updatedExpenses = [...updatedExpenses, newExpense];
      }

      return {
        ...prev,
        expenses: updatedExpenses,
        cards: updatedCards
      };
    });

    setEditingExpense(null);
  };

  const deleteExpense = (id) => {
    const expenseToDelete = data.expenses.find((expense) => expense.id === id);

    if (expenseToDelete?.method === 'Tarjeta' && expenseToDelete.cardId) {
      setData((prev) => ({
        ...prev,
        expenses: prev.expenses.filter((expense) => expense.id !== id),
        cards: applyCardUsageDelta(prev.cards, expenseToDelete.cardId, -Number(expenseToDelete.amount))
      }));
      return;
    }

    setData((prev) => ({
      ...prev,
      expenses: prev.expenses.filter((expense) => expense.id !== id)
    }));
  };

  const addCard = (card) => {
    const newCard = {
      ...card,
      id: Date.now().toString()
    };

    setData((prev) => ({
      ...prev,
      cards: [...prev.cards, newCard]
    }));
  };

  const editCard = (card) => {
    setData((prev) => ({
      ...prev,
      cards: prev.cards.map((item) => (item.id === card.id ? card : item))
    }));
  };

  const deleteCard = (id) => {
    setData((prev) => ({
      ...prev,
      cards: prev.cards.filter((card) => card.id !== id),
      cash: {
        ...prev.cash,
        payments: (prev.cash?.payments || []).filter((payment) => payment.cardId !== id)
      }
    }));
  };

  const simulateCardPayment = ({ cardId, amount }) => {
    const paymentAmount = Number(amount || 0);
    if (!cardId || paymentAmount <= 0) return;

    setData((prev) => {
      const card = prev.cards.find((item) => item.id === cardId);
      if (!card) return prev;

      const safeAmount = Math.min(paymentAmount, Number(card.used || 0));
      if (safeAmount <= 0) return prev;

      const paymentRecord = {
        id: `card-payment-${Date.now()}`,
        cardId: card.id,
        cardName: card.name,
        amount: safeAmount,
        date: new Date().toISOString(),
        createdAt: new Date().toISOString()
      };

      return normalizeData({
        ...prev,
        cards: prev.cards.map((item) => (
          item.id === cardId
            ? { ...item, used: Math.max(0, Number(item.used || 0) - safeAmount) }
            : item
        )),
        cash: {
          ...prev.cash,
          payments: [...(prev.cash?.payments || []), paymentRecord]
        }
      });
    });
  };

  const updateSettings = (newSettings) => {
    setData((prev) => normalizeData({
      ...prev,
      ...newSettings,
      cash: newSettings.cash
        ? {
            ...prev.cash,
            ...newSettings.cash,
            payments: newSettings.cash.payments ?? prev.cash?.payments ?? [],
            savings: newSettings.cash.savings ?? prev.cash?.savings ?? { entries: [] }
          }
        : prev.cash,
      goals: newSettings.goals
        ? {
            ...prev.goals,
            ...newSettings.goals
          }
        : prev.goals
    }));
  };

  const resetData = () => {
    const freshData = {
      cash: { income: 0, entries: [createPrimaryIncomeEntry(0)], savings: { entries: [] } },
      expenses: [],
      cards: [],
      goals: { type: 'weekly', amount: 0 },
      currentDate: new Date().toISOString()
    };

    setData(normalizeData(freshData));
    localStorage.removeItem(getScopedStorageKey(session));
  };

  const handleOpenExpenseModal = (expense = null) => {
    setEditingExpense(expense);
    setShowExpenseModal(true);
  };

  if (!session) {
    return (
      <AnimatePresence mode="wait">
        <motion.div key="login-shell" className="relative min-h-screen">
          <LoginScreen
            onGuestAccess={handleGuestAccess}
            onProviderSelect={handleProviderSelect}
            onEmailCodeVerify={handleEmailCodeVerify}
            onDirectAdminLogin={handleDirectAdminLogin}
            isTransitioning={isEnteringApp}
            loginError={loginError}
            cloudReady={isFirebaseConfigured}
          />

          <AnimatePresence>
            {isEnteringApp && (
              <motion.div
                key="login-to-dashboard"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.45, ease: 'easeOut' }}
                className="app-entry-overlay"
              >
                <motion.div
                  initial={{ scale: 0.95, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ duration: 0.42, delay: 0.08 }}
                  className="app-entry-card"
                >
                  <div className="app-entry-grid" />
                  <motion.div
                    animate={{ x: ['-10%', '112%'] }}
                    transition={{ duration: 1.05, repeat: Infinity, ease: 'easeInOut' }}
                    className="app-entry-scan"
                  />
                  <div className="app-entry-badge">Preparando dashboard</div>
                  <Wallet weight="fill" className="app-entry-icon" />
                  <div className="app-entry-copy">
                    
                    <h2>Entrando a tu panel financiero</h2>
                    <p>Sincronizando tus movimientos y preparando tu panel financiero.</p>
                  </div>
                  <div className="app-entry-progress">
                    <span />
                  </div>
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>

          {renderLogoutTransition()}
        </motion.div>
      </AnimatePresence>
    );
  }

  return (
    <div className="min-h-screen bg-[#FAFAF9] relative">
      <Layout
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        onAddExpense={() => handleOpenExpenseModal()}
        onAddIncome={() => setShowIncomeModal(true)}
        onAddCash={() => setActiveTab('settings')}
        onLogout={handleLogout}
        session={session}
      >
        <AnimatePresence mode="wait">
          {activeTab === 'home' && (
            <motion.div
              key="home"
              initial={{ opacity: 0, y: 18, scale: 0.988, filter: 'blur(10px)' }}
              animate={{ opacity: 1, y: 0, scale: 1, filter: 'blur(0px)' }}
              exit={{ opacity: 0, y: -12, filter: 'blur(8px)' }}
              transition={{ duration: 0.52, ease: 'easeOut' }}
            >
              <Dashboard
                data={data}
                onNavigate={setActiveTab}
                onAddExpense={() => handleOpenExpenseModal()}
                onLogout={handleLogout}
              />
            </motion.div>
          )}

          {activeTab === 'expenses' && (
            <motion.div
              key="expenses"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.28 }}
            >
              <ExpensesList
                expenses={data.expenses}
                cards={data.cards}
                cardPayments={data.cash?.payments || []}
                onEdit={handleOpenExpenseModal}
                onDelete={deleteExpense}
              />
            </motion.div>
          )}

          {activeTab === 'cards' && (
            <motion.div
              key="cards"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.28 }}
            >
              <CardsPanel
                cards={data.cards}
                cashAvailable={data.cash.income - data.expenses.filter((expense) => {
                  const expDate = parseDateOnly(expense.date);
                  const current = new Date(data.currentDate);
                  if (!expDate) return false;
                  return (
                    expDate.getMonth() === current.getMonth() &&
                    expDate.getFullYear() === current.getFullYear() &&
                    expense.method === 'Cash'
                  );
                }).reduce((sum, expense) => sum + expense.amount, 0) - getMonthlyCardPaymentsTotal(data.cash.payments, data.currentDate) - getSavingsBalance(data.cash)}
                onAdd={addCard}
                onEdit={editCard}
                onDelete={deleteCard}
                onSimulatePayment={simulateCardPayment}
              />
            </motion.div>
          )}

          {activeTab === 'stats' && (
            <motion.div
              key="stats"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.28 }}
            >
              <Statistics data={data} />
            </motion.div>
          )}

          {activeTab === 'calendar' && (
            <motion.div
              key="calendar"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.28 }}
            >
              <CalendarView
                expenses={data.expenses}
                currentDate={data.currentDate}
              />
            </motion.div>
          )}

          {activeTab === 'settings' && (
            <motion.div
              key="settings"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.28 }}
            >
              <Settings
                data={data}
                onUpdate={updateSettings}
                onReset={resetData}
                session={session}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </Layout>

      <IncomeModal
        isOpen={showIncomeModal}
        onClose={() => setShowIncomeModal(false)}
        data={data}
        onUpdate={updateSettings}
      />

      <ExpenseModal
        isOpen={showExpenseModal}
        onClose={() => {
          setShowExpenseModal(false);
          setEditingExpense(null);
        }}
        onSave={addExpense}
        cards={data.cards}
        editingExpense={editingExpense}
        cashData={{
          income: data.cash.income,
          spent: data.expenses
            .filter((expense) => {
              const expDate = parseDateOnly(expense.date);
              const current = new Date(data.currentDate);
              if (!expDate) return false;
              return (
                expDate.getMonth() === current.getMonth() &&
                expDate.getFullYear() === current.getFullYear() &&
                expense.method === 'Cash'
              );
            })
            .reduce((sum, expense) => sum + expense.amount, 0),
          cardPayments: getMonthlyCardPaymentsTotal(data.cash.payments, data.currentDate),
          reservedSavings: getSavingsBalance(data.cash)
        }}
      />

      {renderLogoutTransition()}
    </div>
  );
}

export default App;
